### ISSUE TITLE
Link doesn't work in readme file

### ISSUE THREAD

**Issue by JohannaPedersen** [AU-BCE-EE/ALFAM2-data#48]
Link in L70 of readme file does not work.

**Comment by sashahafner** [comment]
Thanks.
Looks like GitHub Pages has changed :(
https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site
Trying to sort it out

**Comment by sashahafner** [comment]
Oh duh.
The problem was just an old URL with sashahafner instead of au-bce-ee.

**Comment by sashahafner** [comment]
Works now.
Not sure I needed to add .nojekyll afterall.
>GitHub Pages now uses GitHub Actions to execute the Jekyll build. When using a branch as the source of your build, GitHub Actions must be enabled in your repository if you want to use the built-in Jekyll workflow. Alternatively, if GitHub Actions is unavailable or disabled, adding a .nojekyll file to the root of your source branch will bypass the Jekyll build process and deploy the content directly. For more information on enabling GitHub Actions, see "[Managing GitHub Actions settings for a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository)."

https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site
